import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const scriptsDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectDirectory = path.resolve(scriptsDirectory, '..');
const indexPath = path.join(projectDirectory, 'index.html');
const applicationPath = path.join(projectDirectory, 'script.js');
const outputDirectory = path.join(projectDirectory, 'en');
const outputPath = path.join(outputDirectory, 'index.html');

const applicationSource = fs.readFileSync(applicationPath, 'utf8');
const translationStart = applicationSource.indexOf('const translations = ');
const translationEnd = applicationSource.indexOf('\n\nconst whatsappLink');
if (translationStart < 0 || translationEnd < 0) throw new Error('Translation object could not be located.');

const translationExpression = applicationSource
  .slice(translationStart + 'const translations = '.length, translationEnd)
  .trim()
  .replace(/;$/, '');
const translations = vm.runInNewContext(`(${translationExpression})`, Object.create(null));
const english = translations.en;

const escapePattern = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const escapeText = (value) => String(value)
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;');
const escapeAttribute = (value) => escapeText(value).replaceAll('"', '&quot;');

const replaceNodeContent = (source, dataAttribute, values, allowHtml) => {
  let result = source;
  Object.entries(values).forEach(([key, value]) => {
    const pattern = new RegExp(
      `(<([a-z][\\w-]*)[^>]*\\s${dataAttribute}="${escapePattern(key)}"[^>]*>)[\\s\\S]*?(</\\2>)`,
      'gi'
    );
    result = result.replace(pattern, (_, opening, __, closing) => (
      `${opening}${allowHtml ? value : escapeText(value)}${closing}`
    ));
  });
  return result;
};

const replaceTranslatedAttributes = (source, dataAttribute, targetAttribute, values) => {
  let result = source;
  Object.entries(values).forEach(([key, value]) => {
    const tagPattern = new RegExp(`<[^>]*\\s${dataAttribute}="${escapePattern(key)}"[^>]*>`, 'gi');
    result = result.replace(tagPattern, (tag) => (
      tag.replace(
        new RegExp(`${targetAttribute}="[^"]*"`, 'i'),
        `${targetAttribute}="${escapeAttribute(value)}"`
      )
    ));
  });
  return result;
};

const replaceMetaContent = (source, selectorFragment, value) => {
  const tagPattern = new RegExp(`<meta[^>]*${selectorFragment}[^>]*>`, 'i');
  return source.replace(tagPattern, (tag) => (
    tag.replace(/content="[^"]*"/i, `content="${escapeAttribute(value)}"`)
  ));
};

let html = fs.readFileSync(indexPath, 'utf8');
html = html.replace('<!doctype html>', '<!doctype html>\n<!-- Auto-generated by scripts/generate-en.mjs. Edit index.html and script.js, then regenerate. -->');
html = html.replace('<html lang="tr">', '<html lang="en">');
html = replaceNodeContent(html, 'data-i18n', english, false);
html = replaceNodeContent(html, 'data-i18n-html', english, true);
html = replaceTranslatedAttributes(html, 'data-i18n-alt', 'alt', english);
html = replaceTranslatedAttributes(html, 'data-i18n-title', 'title', english);
html = replaceTranslatedAttributes(html, 'data-i18n-aria-label', 'aria-label', english);

html = html.replace(/<title>[\s\S]*?<\/title>/i, `<title>${escapeText(english.documentTitle)}</title>`);
html = replaceMetaContent(html, 'id="metaDescription"', english.metaDescription);
html = replaceMetaContent(html, 'name="keywords"', 'Liora Ortaca, MEF Yapı Liora Ortaca, Ortaca residences for sale, Muğla property, Cumhuriyet District, boutique residences');
html = replaceMetaContent(html, 'id="ogLocale"', 'en_US');
html = replaceMetaContent(html, 'property="og:locale:alternate"', 'tr_TR');
html = replaceMetaContent(html, 'id="ogTitle"', english.documentTitle);
html = replaceMetaContent(html, 'id="ogDescription"', 'A boutique natural-stone residential project for eight select families in Ortaca, Muğla. Contact us about the final four residences.');
html = replaceMetaContent(html, 'id="ogImageAlt"', 'Liora Ortaca boutique residences at sunset');
html = replaceMetaContent(html, 'id="twitterTitle"', english.documentTitle);
html = replaceMetaContent(html, 'id="twitterDescription"', 'Boutique natural-stone residences in Ortaca, Muğla. Contact us about the final four of eight homes.');
html = replaceMetaContent(html, 'name="twitter:image:alt"', 'Liora Ortaca boutique residences at sunset');
html = html
  .replace(
    '<link rel="canonical" href="https://www.lioraortaca.com/" />',
    '<link rel="canonical" href="https://www.lioraortaca.com/en" />'
  )
  .replace(
    '<meta property="og:url" content="https://www.lioraortaca.com/" />',
    '<meta property="og:url" content="https://www.lioraortaca.com/en" />'
  );

html = html
  .replace('data-language="tr" aria-pressed="true"', 'data-language="tr" aria-pressed="false"')
  .replace('data-language="en" aria-pressed="false"', 'data-language="en" aria-pressed="true"')
  .replace('aria-label="Menüyü aç"', `aria-label="${escapeAttribute(english.menuLabel)}"`)
  .replace('aria-label="WhatsApp ile bilgi alın"', `aria-label="${escapeAttribute(english.whatsappFloating)}"`)
  .replace('aria-label="Bildirimi küçült"', `aria-label="${escapeAttribute(english.whatsappDismiss)}"`);

const englishWhatsappUrl = `https://wa.me/905469108052?text=${encodeURIComponent(english.whatsappMessage)}`;
html = html.replace(/href="https:\/\/wa\.me\/905469108052\?text=[^"]*"/g, `href="${englishWhatsappUrl}"`);

fs.mkdirSync(outputDirectory, { recursive: true });
fs.writeFileSync(outputPath, html, 'utf8');
console.log(`Generated ${path.relative(projectDirectory, outputPath)}`);
